import { Routes } from '@angular/router';
import { DistribuidoraDashboardComponent } from './pages/dashboard/distribuidora-dashboard.component';
import { ListaClientesComponent } from './clientes/pages/lista-clientes/lista-clientes.component';
import { NuevoClienteComponent } from './clientes/pages/nuevo-cliente/nuevo-cliente.component';
import { DetalleClienteComponent } from './clientes/pages/detalle-cliente/detalle-cliente.component';
import { MisValesComponent } from './vales/pages/mis-vales/mis-vales.component';
import { SolicitarValeComponent } from './vales/pages/solicitar-vale/solicitar-vale.component';
import { HistorialPuntosComponent } from './puntos/pages/historial-puntos/historial-puntos.component';
import { ListaConciliacionesComponent } from './conciliaciones/pages/lista-conciliaciones/lista-conciliaciones.component';
import { TransferenciasComponent } from './clientes/pages/transferencias/transferencias.component';
import { AumentoCreditoComponent } from './creditos/pages/aumento-credito/aumento-credito.component';
import { ListaRelacionesComponent } from './relaciones/pages/lista-relaciones/lista-relaciones.component';
import { DetalleRelacionComponent } from './relaciones/pages/detalle-relacion/detalle-relacion.component';
import { EstadoCuentaComponent } from './relaciones/pages/estado-cuenta/estado-cuenta.component';
import { CambiarPasswordComponent } from '../../shared/components/cambiar-password/cambiar-password.component';

export const DISTRIBUIDORA_ROUTES: Routes = [
  { path: '', component: DistribuidoraDashboardComponent },
  { path: 'clientes', component: ListaClientesComponent },
  { path: 'clientes/nuevo', component: NuevoClienteComponent },
  { path: 'clientes/transferencias', component: TransferenciasComponent },
  { path: 'clientes/:id', component: DetalleClienteComponent },
  { path: 'vales', component: MisValesComponent },
  { path: 'vales/solicitar', component: SolicitarValeComponent },
  { path: 'puntos/historial', component: HistorialPuntosComponent },
  { path: 'conciliaciones', component: ListaConciliacionesComponent },
  { path: 'creditos/aumento', component: AumentoCreditoComponent },
  { path: 'relaciones', component: ListaRelacionesComponent },
  { path: 'relaciones/:id', component: DetalleRelacionComponent },
  { path: 'estado-cuenta', component: EstadoCuentaComponent },
  { path: 'cuenta/contrasena', component: CambiarPasswordComponent }
];
