import { Routes } from '@angular/router';
import { GerenteDashboardComponent } from './pages/dashboard/gerente-dashboard.component';
import { ListaSolicitudesComponent } from './alta-proveedor/pages/lista-solicitudes/lista-solicitudes.component';
import { DetalleSolicitudComponent } from './alta-proveedor/pages/detalle-solicitud/detalle-solicitud.component';
import { ListaDistribuidorasComponent } from './distribuidoras/pages/lista-distribuidoras/lista-distribuidoras.component';
import { DetalleDistribuidoraComponent } from './distribuidoras/pages/detalle-distribuidora/detalle-distribuidora.component';
import { ListaProductosComponent } from './productos/pages/lista-productos/lista-productos.component';
import { ValesPendientesComponent } from './vales/pages/vales-pendientes/vales-pendientes.component';
import { ListaRelacionesComponent } from './relaciones/pages/lista-relaciones/lista-relaciones.component';
import { DetalleRelacionComponent } from './relaciones/pages/detalle-relacion/detalle-relacion.component';
import { ListaMorososComponent } from './reportes/pages/lista-morosos/lista-morosos.component';
import { ListaConciliacionesComponent } from './conciliaciones/pages/lista-conciliaciones/lista-conciliaciones.component';
import { AutorizacionesPendientesComponent } from './conciliaciones/pages/autorizaciones-pendientes/autorizaciones-pendientes.component';
import { ConfiguracionesComponent } from './configuraciones/pages/configuraciones/configuraciones.component';
import { EdicionesPendientesComponent } from './clientes/pages/ediciones-pendientes/ediciones-pendientes.component';
import { ListaNotificacionesComponent } from './notificaciones/pages/lista-notificaciones/lista-notificaciones.component';

export const GERENTE_ROUTES: Routes = [
  { path: '', component: GerenteDashboardComponent },
  { path: 'solicitudes', component: ListaSolicitudesComponent },
  { path: 'solicitudes/:id', component: DetalleSolicitudComponent },
  { path: 'distribuidoras', component: ListaDistribuidorasComponent },
  { path: 'distribuidoras/:id', component: DetalleDistribuidoraComponent },
  { path: 'productos', component: ListaProductosComponent },
  { path: 'vales', component: ValesPendientesComponent },
  { path: 'relaciones', component: ListaRelacionesComponent },
  { path: 'relaciones/:id', component: DetalleRelacionComponent },
  { path: 'reportes/morosos', component: ListaMorososComponent },
  { path: 'conciliaciones', component: ListaConciliacionesComponent },
  { path: 'conciliaciones/autorizaciones', component: AutorizacionesPendientesComponent },
  { path: 'configuraciones', component: ConfiguracionesComponent },
  { path: 'clientes/ediciones', component: EdicionesPendientesComponent },
  { path: 'notificaciones', component: ListaNotificacionesComponent }
];
