import { Routes } from '@angular/router';
import { GerenteDashboardComponent } from './pages/dashboard/gerente-dashboard.component';
import { ListaSolicitudesComponent } from './alta-proveedor/pages/lista-solicitudes/lista-solicitudes.component';
import { DetalleSolicitudComponent } from './alta-proveedor/pages/detalle-solicitud/detalle-solicitud.component';
import { ListaDistribuidorasComponent } from './distribuidoras/pages/lista-distribuidoras/lista-distribuidoras.component';
import { DetalleDistribuidoraComponent } from './distribuidoras/pages/detalle-distribuidora/detalle-distribuidora.component';
import { ListaProductosComponent } from './productos/pages/lista-productos/lista-productos.component';
import { ListaRelacionesComponent } from './relaciones/pages/lista-relaciones/lista-relaciones.component';
import { DetalleRelacionComponent } from './relaciones/pages/detalle-relacion/detalle-relacion.component';
import { ListaMorososComponent } from './reportes/pages/lista-morosos/lista-morosos.component';
import { ListaConciliacionesComponent } from './conciliaciones/pages/lista-conciliaciones/lista-conciliaciones.component';
import { AutorizacionesPendientesComponent } from './conciliaciones/pages/autorizaciones-pendientes/autorizaciones-pendientes.component';
import { ConfiguracionesComponent } from './configuraciones/pages/configuraciones/configuraciones.component';
import { EdicionesPendientesComponent } from './clientes/pages/ediciones-pendientes/ediciones-pendientes.component';
import { ReasignarCoordinadorComponent } from './distribuidoras/pages/reasignar-coordinador/reasignar-coordinador.component';
import { TransferenciasPendientesComponent } from './clientes/pages/transferencias-pendientes/transferencias-pendientes.component';
import { AumentoCreditoPendientesComponent } from './distribuidoras/pages/aumento-credito-pendientes/aumento-credito-pendientes.component';
import { PersonalComponent } from './personal/pages/personal/personal.component';
import { ReasignarGerenteComponent } from './personal/pages/reasignar-gerente/reasignar-gerente.component';
import { MisAutorizacionesComponent } from './autorizaciones/pages/mis-autorizaciones/mis-autorizaciones.component';
import { ConsultarValesComponent } from './vales/pages/consultar-vales/consultar-vales.component';
import { ReembolsoExcedentePendientesComponent } from './vales/pages/reembolso-excedente-pendientes/reembolso-excedente-pendientes.component';
import { CambiarPasswordComponent } from '../../shared/components/cambiar-password/cambiar-password.component';

export const GERENTE_ROUTES: Routes = [
  { path: '', component: GerenteDashboardComponent },
  { path: 'solicitudes', component: ListaSolicitudesComponent },
  { path: 'solicitudes/:id', component: DetalleSolicitudComponent },
  { path: 'distribuidoras', component: ListaDistribuidorasComponent },
  { path: 'distribuidoras/reasignar-coordinador', component: ReasignarCoordinadorComponent },
  { path: 'distribuidoras/aumento-credito', component: AumentoCreditoPendientesComponent },
  { path: 'distribuidoras/:id', component: DetalleDistribuidoraComponent },
  { path: 'productos', component: ListaProductosComponent },
  { path: 'relaciones', component: ListaRelacionesComponent },
  { path: 'relaciones/:id', component: DetalleRelacionComponent },
  { path: 'reportes/morosos', component: ListaMorososComponent },
  { path: 'conciliaciones', component: ListaConciliacionesComponent },
  { path: 'conciliaciones/autorizaciones', component: AutorizacionesPendientesComponent },
  { path: 'configuraciones', component: ConfiguracionesComponent },
  { path: 'clientes/ediciones', component: EdicionesPendientesComponent },
  { path: 'clientes/transferencias', component: TransferenciasPendientesComponent },
  { path: 'personal', component: PersonalComponent },
  { path: 'personal/reasignar-gerente', component: ReasignarGerenteComponent },
  { path: 'autorizaciones', component: MisAutorizacionesComponent },
  { path: 'vales', component: ConsultarValesComponent },
  { path: 'vales/reembolso-excedente', component: ReembolsoExcedentePendientesComponent },
  { path: 'cuenta/contrasena', component: CambiarPasswordComponent }
];
